### ISSUE TITLE
android 6.0

### ISSUE THREAD

**Issue by hoomanmmd** [clickyab/android-sample#16]
this lib keep asking location permission on API 23 every time it runs whether you accept it or not.
and also please add a method to load ad programmatically.
tnx.

**Comment by psamim** [comment]
Dear,

I will check into API 23 problem, thanks for reporting the issue.

And what do you mean by loading programmatically?

Thanks

**Comment by hoomanmmd** [comment]
I meant loading ad without XML code bur just with JAVA code and add it to view.

**Comment by psamim** [comment]
@appgozar Support for API 23 permission system was added in version 1.2.6

**Comment by psamim** [comment]
Another issue will be opened for loading ads programmatically.
