### ISSUE TITLE
Error:Execution failed for task ':app:mysa'. > Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by smaznet** [clickyab/android-sample#18]
Error:Execution failed for task ':app.
> Manifest merger failed with multiple errors, see logs

**Comment by psamim** [comment]
Would you please show the logs?

**Comment by smaznet** [comment]
fixed by adding this line to "application" tag in manifetst
``` tools:replace="android:allowBackup,android:label" ```
