### ISSUE TITLE
Annoying ProgressBar!!

### ISSUE THREAD

**Issue by IRMobydick** [clickyab/android-sample#2]
Hi there,
There is an orange loading indicator before Clickyab Banner object loads the Ads!!
How can remove it!

**Comment by psamim** [comment]
Hi,

I will provide a method to override the default progress bar or remove it entirely, in the next version in a few days.

Thanks

**Comment by IRMobydick** [comment]
Thanks bro 👍

**Comment by IRMobydick** [comment]
Another issue to remind: This loading indicator also remain on screen when user close the ads!

**Comment by fzerorubigd** [comment]
@IRMobydick could you please open another issue for this? thanks.

**Comment by psamim** [comment]
@IRMobydick SDK is updated to v1.2.1 and now you can override or disable the progress indicator. See **Customizing** in **README**.
