### ISSUE TITLE
Memory Leak - Banner

### ISSUE THREAD

**Issue by IRMobydick** [clickyab/android-sample#21]
`Banner` **Does not release the context** and cause memory leaks!
check this out!

x----- leak data -----x

    In com.******.android:6.3.4:25.
    * com.******.android.activities.******Activity has leaked:
    * GC ROOT thread java.lang.Thread.<Java Local> (named 'AsyncTask #4')
    * references com.clickyab.c$b.a
    * references com.clickyab.Banner.mContext
    * leaks com.******.android.activities.******Activity instance

    * Retaining: 263 KB.
    * Reference Key: 6ca7aa19-6168-492a-9563-ac64a883f462
    * Device: samsung samsung SM-G900H k3gxx
    * Android Version: 6.0.1 API: 23
    * Durations: watch=5020ms, gc=241ms, heap dump=6530ms, analysis=55779ms

**Comment by IRMobydick** [comment]
This is really annoying! please fix it asap!! :(

**Comment by psamim** [comment]
@IRMobydick This should be fixed now in version 1.2.8. Also you can use the library by adding the dependency to your `build.gradle` file (refer to README).

By the way, as a funny note, I used https://github.com/square/leakcanary/ to find the leaks. In the meantime I found various leaks by the Android platform itself.

**Comment by IRMobydick** [comment]
@psamim 
You do right that use LeakCanary 👍 
I'll check this version asap, But we got some crash report on android 6, that your SDK is cause of them!
Now, I have no enough time to check, but till to find the issue you can check this too.

Thanks buddy

**Comment by psamim** [comment]
@IRMobydick I am looking forward to hearing about the crash.

**Comment by IRMobydick** [comment]
In com.******.android:6.3.9:28.
    * com.******.android.activities.******Activity has leaked:
    * GC ROOT static com.******.android.fragments.******Fragment.mBanner
    * references com.clickyab.Banner.mContext
    * leaks com.******.android.activities.******Activity instance

It's still there dude!

**Comment by psamim** [comment]
@IRMobydick No, in your previous log the leak was from `java.lang.Thread.<Java Local> (named 'AsyncTask #4')`. It is different now and the fact that we have not used fragments in our code makes it strange. I will look into it though. I truly thank you for taking your time and reporting it.

**Comment by psamim** [comment]
@IRMobydick From the trace it seems that you use a fragment which holds a reference to the banner. And the banner, which is a view, holds a reference to the activity context. Therefore destroying the fragment leaks the context. Can it be the scenario?

**Comment by IRMobydick** [comment]
@psamim 
No, We got this every where we have Banner in our view ( Activity, fragment).
It's enough to add Banner to xml to get leak! ( my idea is check banner constructor, where you get context and where you release it. )

**Comment by IRMobydick** [comment]
Any progress?

**Comment by psamim** [comment]
@IRMobydick No, `leakcanary` does not show relevant leaks on my devices. Maybe it happens at certain times or on specific platforms. I will dig more into it.
