### ISSUE TITLE
Proguard Rules?

### ISSUE THREAD

**Issue by IRMobydick** [clickyab/android-sample#22]
Hi there, Just let us know the proguard rules, thanks!

**Comment by psamim** [comment]
@IRMobydick Hi, proguard rules are added to README.

**Comment by IRMobydick** [comment]
Thanks buddy 👍

**Comment by IRMobydick** [comment]
It seems you missed close bracket at the end "}" 😉

**Comment by psamim** [comment]
@IRMobydick Thanks! :)
